# Generated by Django 5.1.5 on 2025-02-13 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_logic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=255, unique=True, verbose_name='로그인 ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('kakao', 'Kakao'), ('naver', 'Naver')], max_length=20, verbose_name='소셜 제공자')),
                ('provider_id', models.CharField(max_length=255, unique=True, verbose_name='소셜 제공자 ID')),
                ('access_token', models.TextField(verbose_name='액세스 토큰')),
                ('refresh_token', models.TextField(blank=True, null=True, verbose_name='리프레시 토큰')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('banned', 'Banned')], default='active', max_length=20, verbose_name='상태')),
                ('login_modified_dt', models.DateTimeField(auto_now=True, verbose_name='로그인 수정일')),
                ('login_created_dt', models.DateTimeField(auto_now_add=True, verbose_name='로그인 생성일')),
                ('member_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_account', to=settings.AUTH_USER_MODEL, verbose_name='회원 ID')),
            ],
        ),
    ]
